APP_ID: cli_a4dd097ed038500e
APP_SECRET: xx
APP_ENCRYPT_KEY: xx
APP_VERIFICATION_TOKEN: xxx
BOT_NAME: xxx
DISCORD_MIDJOURNEY_URL: http://127.0.0.1:16008/v1/trigger/midjourney-bot
DISCORD_UPLOAD_URL: http://127.0.0.1:16008/v1/trigger/upload